config:
  app_name: Griffin Web Studio Maintenance Assistant
  session_name: gws_maintenance_session
  main_banner: |
    >>01000111010101110101001100100000010011010010000000110
    >1    _______ _______ _______                        00
    00   ||     |||     |||     ||     MaiNt  aNCe       00
    01   ||  G  |||  W  |||  S  ||     MAI TENA CE       01
    10   ||_____|||_____|||_____||     Ma   En  CE       10
    00   |/_____\|/_____\|/_____\|     Ma       CE  01   00
    00                                                   1<
    01100000001001011001000000100110010101110101011100010<<'
