config:
  app_name: Griffin Web Studio Maintenance Assistant
  session_name: gws_maintenance_session
  main_banner: |
    >>0100011101010111010100110010000001001101001000000011000000
    >>      _______ _______ _______                           11
    >>     ||     |||     |||     ||      MaiNt  aNCe         00
    >>     ||  G  |||  W  |||  S  ||      MAI TENA CE         01
    10     ||_____|||_____|||_____||      Ma   En  CE         <<
    00     |/_____\|/_____\|/_____\|      Ma       CE  01     <<
    11                                                        <<
    0000001100000001001011001000000100110010101110101011100010<<
